### ISSUE TITLE
MinimumSpanningTree-related issues

### ISSUE THREAD

**Issue by jrtom** [jrtom/jung#112]
* `MinimumSpanningTree` generates directed graphs (for interoperation), but they should be undirected
   * `TreeLayout`’s rendering of the MSTs in `MinimumSpanningTreeDemo` seems a bit odd (upside down and rectilinear)

**Comment by tomnelson** [comment]
The MinimumSpanningTreeDemo shows your expected tree upside down because the top row are all 'roots'.

For this strongly connected network of A, B, C:
network:isDirected: false, allowsParallelEdges: true, allowsSelfLoops: false, nodes: [A, B, C], edges: {0=[B, A], 1=[C, A], 2=[C, B]}

The extracted tree is from MinimumSpanningTree.extractFrom(network)  is:
isDirected: true, allowsParallelEdges: false, allowsSelfLoops: false, nodes: [A, B, C], edges: {0=<B -> A>, 1=<C -> A>}

and TreeUtils.roots(tree) gives this:
roots are [B, C]

**Comment by wumpz** [comment]
If MST is an undirected graph, the TreeLayout will not work anymore, because it needs root nodes and there are none without direction. Which layouter should be used instead?

**Comment by jrtom** [comment]
Any of the force-directed layouts should be fine for the undirected graph case.
