### ISSUE TITLE
Guava graphs?

### ISSUE THREAD

**Issue by oliviercailloux** [jrtom/jung#222]
From a cursory look at the Javadoc, it seems like JUNG still uses its own graph structures rather than Guava’s. Although there seems to have been some plans to switch to guava (e.g. [here](https://github.com/google/guava/issues/2411) or [here](https://github.com/google/guava/issues/2651)). Also, the related branch has disappeared.
Have the plans been abandoned?

**Comment by jrtom** [comment]
@oliviercailloux as @jbduncan said, I've been very short on time to devote to JUNG in recent months, but JUNG 3.0 will indeed use Guava's graph structures, and in fact the current master version of the repo is a 3.0 snapshot; the common.graph branch has been merged into master, which is why the common.graph branch no longer exists.

You can see the issues associated with the 3.0 release here: https://github.com/jrtom/jung/projects/1

If you have time and are interested in helping this release get out the door, your help would be sincerely appreciated.  :)
