### ISSUE TITLE
Is it possible to create a graph that has two different types of edges? 

### ISSUE THREAD

**Issue by SND8041** [jrtom/jung#247]
Hi,
I am working on a project in which a network is to be made. The only problem is that I encounter nodes with parallel edges such that two edge can carry different type of information. For example, if A and B are two nodes, it is possible that these are connected by two edges, say e1 & e2, where e1 has a weight "21.5 degrees (direction)" and e2 has a weight "3.0 knots". Well, I understand that units are not necessary to put in, but the numbers can not be added as they represent two different type of information, although they both are real numbers.
Syed

**Comment by jrtom** [comment]
In future, please ask questions like this on StackOverflow; we use "issues" for bug reports, feature requests, and the like, not for answering user questions.

What problem are you trying to solve?  What are you trying to model with this graph?

Since you are asked to supply an edge type at compile time, and Java doesn't support variant types, you can't _directly_ do what you're asking for (just as you can't specify a variant key type for a Java `Map`.
However, depending on your specific requirements, there are a few different approaches you can use that Java and JUNG can support.

(Note: (1) and (2) are almost certainly not what you want, and are included for completeness; (3) or (4) is probably the right answer, depending on your requirements.)

(1) Declare your edge type to be `Object`.  Then you can put arbitrary objects in there, and do `instanceof` checks as needed to figure out what you have.
Advantage: simple to declare
Disadvantages:
* makes your code more complex
* loses compile-time type safety for edge types

(2) Declare your graph edge type to be `MyEdgeSuperType`, which has subtypes `Direction` and `Velocity`.
Advantages: 
* simple to declare
* gives you a bit more type safety than "Object"
Disadvantage: 
* makes your code more complex
* still not very type-safe
* may not be semantically coherent

(1) and (2) also have the property that they couple semantic information about the edge to the graph topology, which may or may not be appropriate.

(3) Declare your graph edge type to be `MyEdge`, that has fields for 'direction' and 'velocity'.
Advantages:
* type safe
* simple to declare and parse
* well-supported by Java
Disadvantage:
* implicitly assumes that each edge has all fields (unless you wrap them with Optional or allow them to be null, and do Optional unwraps/null checks as needed)

(4) Create N separate graphs for each edge type, so one graph contains the 'direction' edges and the other the 'velocity' edges.  (Note that a given node--or edge--can be in as many graphs as desired.)
* Advantages:
* type safe
* simple to declare and parse
Disadvantage:
* has somewhat more memory overhead, may require passing around multiple graph objects

To sum up:
* (1) and (2) are not good options.
* (3) is ideal if the properties are semantically related, and are all present for all edges (which your example suggests is true)
* (3) is OK if the properties are semantically related, and not all are present for all edges.
* (4) is appropriate if the properties are unrelated, or only weakly related, and especially if there is no (positive) correlation between the presence of property A and property B.
Thus, for example, (4) would be a good choice if the edges represent "country A exports > $1B in commodity X to country B", because the commodity graphs are presumably uncorrelated.

One final note: be cautious with defining hash code/equals for your edge types, because the edge objects have to be useable as Map keys.  See this discussion for more details: https://github.com/google/guava/wiki/GraphsExplained#elements-must-be-useable-as-map-keys

Hope this helps.
