### ISSUE TITLE
Barabasi-Albert Probability Calculation Wrong

### ISSUE THREAD

**Issue by JMMarchant** [jrtom/jung#32]
I believe the Barabasi-Albert generator may be incorrect in its probability assignments (both in this and in previous versions of JUNG). Whilst it is noted in the docs that a Lagrangian smoothed version of the original formula is used I believe this still has the issues contained.

The docs state that the original formula proposed by Barabasi and Albert is p(v) = deg(v)/|E| but this is incorrect. The original formula is p(v) = deg(v)/(sum deg(v) for all v) which, via the Handshake Lemma, becomes p(v) = deg(v)/2|E|. This scaling means the probabilities no longer sum to 1 over all vertices.

Similarly, the equation actually utilised has the same issue; whilst the numerator uses degree the denominator uses |E| which once again means that the numerator is scaled compared to the denominator and produces total probabilities exceeding 1.

Unless I'm missing something, this is problematic. Whilst it might still produce graphs exhibiting scale-free properties I cannot state this for sure.

**Comment by jrtom** [comment]
Thanks for the report; please file an issue on GitHub if you think that we
need to fix something.

One thing I'll note is that the Handshake Lemma applies to undirected
graphs specifically.  So I think that the formula is at least sort of
correct for directed graphs, although I'm not sure that the form of
Lagrangian smoothing that Scott used actually generates a proper
probability distribution for directed graphs either.

Technically, it doesn't actually matter whether the values that we're using
for determining whether an edge should be created or not are probabilities,
as long as the proportions are correct, but you may be right (because we're
using Random.nextDouble() without scaling it) that we're not doing this
correctly.



On Fri, Feb 19, 2016 at 12:03 PM, JMMatuku <notifications@github.com> wrote:

> I believe the Barabasi-Albert generator may be incorrect in its
> probability assignments (both in this and in previous versions of JUNG).
> Whilst it is noted in the docs that a Lagrangian smoothed version of the
> original formula is used I believe this still has the issues contained.
>
> The docs state that the original formula proposed by Barabasi and Albert
> is p(v) = deg(v)/|E| but this is incorrect. The original formula is p(v) =
> deg(v)/(sum deg(v) for all v) which, via the Handshake Lemma, becomes p(v)
> = deg(v)/2|E|. This scaling means the probabilities no longer sum to 1 over
> all vertices.
>
> Similarly, the equation actually utilised has the same issue; whilst the
> numerator uses degree the denominator uses |E| which once again means that
> the numerator is scaled compared to the denominator and produces total
> probabilities exceeding 1.
>
> Unless I'm missing something, this is problematic. Whilst it might still
> produce graphs exhibiting scale-free properties I cannot state this for
> sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrtom/jung/issues/32>.
>



-- 
joshua.omadadhain@gmail.com......sites.google.com/site/joshuaomadadhain/
   Joshua O'Madadhain: Information Scientist, Musician, Philosopher-At-Tall
It's that moment of dawning comprehension that I live for.  -- Bill
Watterson
 My opinions are too rational and insightful to be those of any
organization.

**Comment by JMMatuku** [comment]
(I think this is filed as an issue on github, unless I've messed something up or you mean something else; I'm not particularly familiar with the ins-and-outs!)

Yes, I should have clarified that it's primarily an issue for Undirected Graphs; should be fine for Directed as it's using in-degree so the total number of edges should just be the sum of in-degrees. The smoothing should also work for this case as it's only the unbalancing of edge counting that affected it.

That was my first thought too; as long as the relative probabilities are the same, it should be fine. But due to the capping that Random.nextDouble() introduces I think it will produce an unfair advantage for some vertices compared to others. In fact, I think it might be making higher degree nodes _more_ preferential than intended: as their p(v) approaches 1 they have a higher chance of being selected than intended. But I can't say whether the effect of this is uniform or not; are lower degree nodes getting the same probability boost in absolute or relative terms?

**Comment by jrtom** [comment]
(Ah, I should have looked on GitHub first, my bad; I thought that was a GitHub-mediate direct email.  :) )

Yeah, I'd have to sit down and work out what happens for the selection mechanism.  The right answer is probably just to make sure that we hack the denominator so that it's different for directed and undirected graphs.  

If you have time to look into this more, we're happy to accept test-supported pull requests.  :)

**Comment by JMMatuku** [comment]
I've constructed a local version implementing the change anyway so can always tidy it up and put it onto github. What tests in particular are you looking for? I note that the current test for BarabasiAlbert is to ensure the number of edges/nodes at the end is as expected; do you just want to ensure it doesn't break this aspect?

**Comment by jrtom** [comment]
The tests that we have for our random graph generators at the moment are kind of terrible.  :/  In the longer term I want to address that.

Tests for random generators are in general tricky.  I don't want JUNG to have tests that fail with some probability p.  OTOH, not testing the distribution at all seems...foolish.

Here are some suggestions:
* Test extreme cases: 
  - no edges (should fail)
  - no vertices (should fail)
* Test different graph types (directed/undirected, graph/multigraph)

If you really want to get into this, some weak distribution tests that might be appropriate:
  - Verify that edges are not all incident to a single vertex (if the graph is large enough)
  - Verify that each vertex has an incident edge (ditto)
(Of course, if the graphs are big enough then you can start doing more standard statistical tests.)

**Comment by jrtom** [comment]
Thanks for taking care of this!  :)
