### ISSUE TITLE
JUnit should be a test dependency, not a compile one

### ISSUE THREAD

**Issue by jbduncan** [jrtom/jung#49]
When I import JUNG 2.1 into my Gradle project and review my dependencies in IntelliJ, I notice that JUnit 3.8.1 is imported by JUNG as a compile dependency. I believe this should be made a test dependency, because otherwise it gets imported into my project's build artifacts when I don't actually need it.

For my own project, I'm currently working around this by excluding JUnit 3.8.1 from my project's transitive deps as follows:
```gradle
dependencies {
  compile("net.sf.jung:jung-graph-impl:2.1") {
    exclude group: 'junit', module: 'junit'
  }
}
```

I did a quick search of the JUNG codebase, and it seems to me this should be a simple fix of changing `pom.xml` so that the dependency:

```xml
...
<dependencyManagement>
   <dependencies>
     <dependency>
       <groupId>junit</groupId>
       <artifactId>junit</artifactId>
       <version>${junit.version}</version>
     </dependency>
     ...
```

is changed to:
```xml
...
<dependencyManagement>
   <dependencies>
     <dependency>
       <groupId>junit</groupId>
       <artifactId>junit</artifactId>
       <version>${junit.version}</version>
       <scope>test</scope>
     </dependency>
     ...
```

**Comment by jrtom** [comment]
Sorry it took me a while to get to this.  It looks like you're correct; we thought we'd set it up so that the individual pom.xml files were setting the scope for JUnit to test, but apparently we didn't, and doing it in dependencyManagement is a cleaner solution anyway.

Next steps for me: use `mvn dependency:tree` to verify that this is happening on a test project, and that it's specifically _not_ happening after we make this change.

(This probably deserves a minor release to fix this issue.  Sigh.)

**Comment by jrtom** [comment]
This should be fixed by #57.  Please reopen this issue if that doesn't take care of it.

**Comment by jbduncan** [comment]
Thanks, looks like it's solved the issue on me. :smile:

**Comment by jrtom** [comment]
Great!  (Note that we now have a bugfix release (2.1.1) that includes this fix.)

**Comment by jbduncan** [comment]
I actually tested it just now with 2.1.1, so I can confirm this issue is solved in that version. :smiley:
