### ISSUE TITLE
Unexpected behavior with EditingGraphMousePlugin using ObservableGraph

### ISSUE THREAD

**Issue by ry99** [jrtom/jung#51]
Setup: I'm trying to use do some editing using the standard EditingGraphMousePlugin on a visualization that is backed by an ObservableGraph to a DirectedSparseMultigraph. The initialization is roughly this:
`private final DirectedGraph<QueryNode, QueryEdge> graph = new DirectedSparseMultigraph<>();`
`private final ObservableGraph<QueryNode, QueryEdge> observer
			= new ObservableGraph<>( graph );`
`private final Layout<QueryNode, QueryEdge> vizlayout = new StaticLayout<>( observer );`
`private final VisualizationViewer<QueryNode, QueryEdge> view
			= new VisualizationViewer<>( vizlayout );`

Problem: EditingGraphMousePlugin::mousePressed checks to see if the underlying graph (in my case, the observer) is Directed, and if not the edge type is set to UNDIRECTED. However, UNDIRECTED edges cannot be added to my delegate graph.

Possible Solution 1: EditingGraphMousePlugin should check if the underlying graph is actually an observer, and if so, use it's delegate to determine edge type.

Possible Solution 2: EditingGraphMousePlugin should delegate to EdgeSupport to determine edge types if possible.

**Comment by jrtom** [comment]
@ry99 Actually, I think there's a better solution: `EditingGraphMousePlugin::mousePressed()` should check for the default edge type, e.g., instead of:

    EdgeType edgeType = (graph instanceof DirectedGraph)
        ? EdgeType.DIRECTED
        : EdgeType.UNDIRECTED;

it should query the graph for its default edge type, which will do the right thing (i.e., ask the delegate for its default edge type):

    EdgeType edgeType = graph.getDefaultEdgeType();

`mousePressed()` has some idiosyncratic behavior on the [next line](https://github.com/jrtom/jung/blob/d52849c49f69e6b7dc5673a38cd3b358cf818326/jung-visualization/src/main/java/edu/uci/ics/jung/visualization/control/EditingGraphMousePlugin.java#L93) as it does another check to see what the click type was and possibly changes the edge type based on the result, but that shouldn't be a problem for you.

Anyway, this is an easy enough fix so I'll go ahead and do that, although I don't expect to be generating another new release soon.

**Comment by jrtom** [comment]
Fixed in #63.
