### ISSUE TITLE
Support for distributed algorithms

### ISSUE THREAD

**Issue by Safouane** [jrtom/jung#6]
Does this library provide support for distributed algorithms (election for example). If so, is there any sample codes. 
Thanks

**Comment by jrtom** [comment]
Please clarify what kind of support you're looking for.  
Are you asking whether certain specific algorithms are part of JUNG, or whether it's possible to write certain types of algorithms using JUNG?

**Comment by Safouane** [comment]
Both questions are valid.
I need to know if the library support distributed architectures (nodes and vertices that are java threads...). Its not a problem to write these algorithms from scratch? i just need to know if they're supported or not. If so, are there any code samples?

I hope i explained well...

**Comment by jrtom** [comment]
Nodes and edges can be any Java objects that you like, but I don't immediately see how those being threads would actually lead to a distributed architecture.

It sounds like maybe you're asking whether you can write an algorithm using JUNG whose execution is distributed across different machines, or at least different processes (this being the usual definition of "distributed architecture").  Maybe you're asking because the data that you're trying to work with is itself distributed, or is very large, or for some other reason, but it's still not clear what you're trying to accomplish, or what your requirements are.

In any event:
(1) There aren't any existing algorithms that are included in JUNG that work in this way.  
(2) It's probably best to think of JUNG as analogous to the Java Collections Framework classes/interfaces (for the Graph API itself), plus a number of graph-related capabilities.

**Comment by Safouane** [comment]
Your assumption is correct. What i am trying to accomplish is to execute a distributed algorithm using Java hence, using Java "thread" objects.

**Comment by jrtom** [comment]
So I guess I'm not sure what you'd hoped that JUNG would be able to do for you.  It's a graph library, not a library for managing interprocess communication.  I suppose that you could use JUNG to maintain the topology of your interprocess communications (nodes as threads and edges that are communication channels).

Anything else I can help with?

**Comment by Safouane** [comment]
That would be all, thanks for all the clarifications.
