### ISSUE TITLE
Connedted graph task

### ISSUE THREAD

**Issue by sarmadm** [jrtom/jung#67]
I'm

looking for one that helps with Graph of ( characters ) .

I want to design a test task that the user should try to connect characters

by order . For example connect (1) to (2) then (2) to (3) . can Jung help m with this ?

**Comment by jrtom** [comment]
Questions about how to use the library are better for Stack Overflow; issues on GitHub are generally for feature requests or bug reports.

Yes, JUNG is useful for representing graphs, and yes, we provide code to support interactive creation of graphs; you can look at our sample code for examples.  But we would need a clearer description of what you're trying to do in order to determine whether JUNG was a good fit.
