### ISSUE TITLE
Consider refactoring KMeansClusterer to use a user-provided function for generating random numbers

### ISSUE THREAD

**Issue by jbduncan** [jrtom/jung#97]
@jrtom I don't know how likely this is, but I suspect there's a chance that the level of randomness produced by the default `Random` instance that JUNG's `KMeansClusterer` uses to do its job is [not random enough](http://blog.dandyer.co.uk/2008/04/03/a-java-programmers-guide-to-random-numbers-part-1-beyond-javautilrandom/) for everyone.

Consider introducing a method like `public void setRandomNumberSupplier(DoubleSupplier randomNumberSupplier)` or `public void setRandomNumberGenerator(RandomGenerator randomGenerator)` (where `RandomGenerator` would be similar to http://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/random/RandomGenerator.html) to meet this potential need.

**Comment by jbduncan** [comment]
I've quickly investigated JGraphT, and it looks like they only use `Random` for generating random numbers, so there seems to be precedent to just have a `public void setRandom(Random random)` method instead.

**Comment by jrtom** [comment]
I think that _most_ of the places in JUNG that have a random element allow one to provide a Random instance; I think I overlooked it in that case.  (In some cases they only allow you to provide a random seed, but we should just make it a straight-up Random instance.)

Since SecureRandom extends Random, anyone that wants a better-than-default Random instance can use that, so I think that enabling users to specify their own Random instance should suffice.

I'd generally like to switch the classes over to use builders (rather than multiple constructors) to construct instances when there are optional parameters; this would be one such case.

**Comment by wumpz** [comment]
Instead of builders one could use some kind of fluent interface definition as well. Something like

public KMeansClusterer withRandom(Random random) {
   ...
   return this;
}

If I want to contribute here, I need to know which type do you prefer. 

However I prefer this type unless you have to hide the constructor of your class. But at the end it is a matter of taste I think.

**Comment by wumpz** [comment]
@jrtom Or does this mean to replace every ocurance of setSeed to setRandom?

**Comment by jrtom** [comment]
(I think that there was a bogus connection made between this issue and a pull request that accidentally closed this issue.)

@wumpz to answer your questions:

(1) Yes, given that we want to allow people to specify their own `Random` instances, I think that it's redundant (and possibly confusing) to also allow people to separately specify the random seed; they can do that on the supplied `Random` instance if desired.

(2) I'm not sure what distinction you're drawing between creating a Builder and using a fluent style; part of the whole point of the Builder pattern is to enable creating the necessary state in a fluent style.

I speculate that the difference you're referring to is whether you've got a separate `KMeansClustererBuilder` type that's building up the state, or if you're doing that all on the `KMeansClusterer` type itself.  If that's the distinction you mean, I think it's generally better to use a Builder: as noted in Bloch's _Effective Java_, that (a) means that you don't have to worry about the object being built being in a possibly inconsistent state, and (b) allows the object being built to be immutable.

Hope that helps; let's continue this discussion.

**Comment by wumpz** [comment]
@jrtom your speculation is right. However a Builder in my understanding is not necessary a fluent interface. I think, that was another point, why I was asking.

Now this `setRandom` is in `KMeansClusterer`. The logical way forward would be to add this `setRandom` everywhere a `setSeed` (for a Random) is and remove those `setSeeds`.
